#!/bin/bash

commit_message=$(date +%d/%m/%Y)
runtime=~/Boring_Stuff/Logfiles/Runtimes/"$0_runtime"
git_result=~/Boring_Stuff/Logfiles/Results/"$0_results"

git_function(){
git init
git add .
git commit -m "$commit_message"
git push 
}

git_function  
echo "Changes pushed" >>$git_result
echo "$0 script ran on $(date)" >>$runtime
